M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date mié 28 sep 2022 21:06:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-28T21:06:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X104.36Y-139.16
X185.64Y-118.84
T0
M30
